export const navIcons = [
  {
    id: '1',
    componentName: 'DoomPlayer',
    iconSrc: require('../../assets/icons/doom.png'),
    iconMaskSrc: require('../../assets/icons/doomWhite.png'),
    altText: 'doom-icon',
    ariaLabel: 'DoomPlayer',
    selected: false,
    tooltipText: 'DoomPlayer',
  },
  {
    id: '2',
    componentName: 'ThemeSelector',
    iconSrc: require('../../assets/icons/theme.png'),
    iconMaskSrc: require('../../assets/icons/themeWhite.png'),
    altText: 'theme-icon',
    ariaLabel: 'ThemeSelector',
    selected: true,
    tooltipText: 'Theme Selector',
  },
  {
    id: '3',
    componentName: 'Tab Management',
    iconSrc: require('../../assets/icons/tabclose.png'),
    iconMaskSrc: require('../../assets/icons/tabcloseWhite.png'),
    altText: 'tabclose-icon',
    ariaLabel: 'Tab Management',
    selected: false,
    tooltipText: 'Tab Management',
  },
  {
    id: '4',
    componentName: 'Json',
    iconSrc: require('../../assets/icons/json.png'),
    iconMaskSrc: require('../../assets/icons/jsonWhite.png'),
    altText: 'json-icon',
    ariaLabel: 'JsonViewer',
    selected: true,
    tooltipText: 'Json Viewer',
  },
  {
    id: '5',
    componentName: 'CodeControls',
    iconSrc: require('../../assets/icons/history.png'),
    iconMaskSrc: require('../../assets/icons/historyWhite.png'),
    altText: 'history-icon',
    ariaLabel: 'CodeControls',
    selected: false,
    tooltipText: 'Code Controls',
  },
  {
    id: '6',
    componentName: 'Geolocation',
    iconSrc: require('../../assets/icons/geolocation.png'),
    iconMaskSrc: require('../../assets/icons/geolocationWhite.png'),
    altText: 'location-icon',
    ariaLabel: 'Geolocation',
    selected: false,
    tooltipText: 'Geolocation',
  },
  {
    id: '7',
    componentName: 'UserAgents',
    iconSrc: require('../../assets/icons/userAgent.png'),
    iconMaskSrc: require('../../assets/icons/userAgentWhite.png'),
    altText: 'agent-icon',
    ariaLabel: 'UserAgents',
    selected: false,
    tooltipText: 'User Agents',
  },
  {
    id: '8',
    componentName: 'Info',
    iconSrc: require('../../assets/icons/information.png'),
    iconMaskSrc: require('../../assets/icons/informationWhite.png'),
    altText: 'info-icon',
    ariaLabel: 'Info',
    selected: false,
    tooltipText: 'Info',
  },
];
