import { State } from './types';

export default {
  getPIDState: (state: State) => (ariaLabel: string) => state.PIDStateMap?.get(ariaLabel),
  getDraggableElements: (state: State) => state.draggableElements,
  getTooltipText: (state: State) => state.tooltipText,
  getTooltipX: (state: State) => state.tooltipX,
  getTooltipY: (state: State) => state.tooltipY,
  getCurrentComponent: (state: State) => state.currentComponent,
  getJsonObjects: (state: State) => state.jsonObjects,
  getTimeZone: (state: State) => state.timeZone,
  getLocale: (state: State) => state.locale,
  getLatitude: (state: State) => state.latitude,
  getLongitude: (state: State) => state.longitude,
  getDefaultView: (state: State) => state.defaultView,
  getFeedbackMessage: (state: State) => state.feedbackMessage,
  getLanguage: (state: State) => state.language,
  getMonacoTheme: (state: State) => state.monacoTheme,
  getShowModal: (state: State) => state.showModal,
  getCrazyMode: (state: State) => state.crazyModeEnabled,
  getTabWidth: (state: State) => state.tabWidth,
  getTabManagementEnabled: (state: State) => state.tabManagementEnabled,
  getTabSetPoint: (state: State) => state.tabSetPoint,
  getTheme: (state: State) => state.themeData,
  getTooltipTheme: (state: State) => state.tooltipTheme,
  getUserAgent: (state: State) => state.userAgent,
  getSelectedTheme: (state: State) => state.selectedTheme,
  getMonacoContainer: (state: State) => state.monacoContainer,
  getEditorInstance: (state: State) => state.editorInstance,
};
